### PR TITLE
feat: return error when form data is empty

### LINKED ISSUE #53: Return decent content-type error
Apparently it is not clear at this time if the client does not send form-data.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #53 
Screenshot 2023-08-16 at 8 07 05 PM

### CODE REVIEW

**Comment by bumi** [comment]
for which endpoints is this?

**Comment by im-adithya** [comment]
only `/oauth/authorize`

**Comment by bumi** [comment]
I see. which is consumed from the rails app. 
👍

**Comment by im-adithya** [comment]
Not just `/oauth/authorize` but also the ones which need authorization (ListClientHandler, UpdateClientHandler, DeleteClientHandler)

**Review by kiwiidb — APPROVED** [review]

**Pull request merged**
