### PR TITLE
add loggin middleware

### LINKED ISSUE #54: Switch to JSON logging
With JSON loggin better montoring queries can be made

For example with the current log line it is more difficult to montor failed calls: 
```
10.244.4.138 - - [06/May/2023:11:17:45 +0000] "POST /oauth/token HTTP/1.1" 401 285 "" "axios/0.27.2"
```

### PR DESCRIPTION
**Pull request by kiwiidb**
Fixes #54 
- Add a JSON formatter for JSON logs so Datadog is happy
- Write custom logging middleware to log request/response metrics.

```
{"bytes_out":46,"host":"localhost:8081","id":"","latency":0.005630833,"level":"info",
"msg":"","referer":"","remote_ip":"","status":401,"time":"2023-07-19T14:24:02+02:00",
"uri":"/balance","user_agent":"HTTPie/3.2.2"}
```

### CODE REVIEW

**Comment by bumi** [comment]
nice! is the app and user_id available on that level to add it?

**Comment by kiwiidb** [comment]
It's probably possible to write more custom code (eg. a fork of the httpsnoop dependency to add the user id) so we can capture the user id as well, but I looked into it and it did not seem straightforward.
Don't really know what you mean by "the app", the log line does include the user agent though.

**Comment by bumi** [comment]
with the `app` I mean the client id 
so in the logs it can be monitored where the requests come from

**Comment by kiwiidb** [comment]
This can probably be done as well but would require some more custom code.

**Comment by bumi** [comment]
Do you have a pointer how this could be done? 
Is there some request context where something can be added like in echo? 
would be nice for monitoring/analytics.

**Pull request merged**
